name: localuf
channels:
  - conda-forge
dependencies:
  - python
  - sphinx
  - ipykernel
  - ipywidgets
  - matplotlib
  - networkx
  - pandas
  - pytest
  - scipy
  - snakeviz
  - statsmodels
  - hatch
  - pip
  - pip:
      - pymatching
      - stim